import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Building,
  Building2,
  Cpu,
  Droplets,
  Flame,
  HardHat,
  HeartPulse,
  Home,
  HousePlus,
  Landmark,
  Leaf,
  Library,
  Megaphone,
  Package,
  Palette,
  PawPrint,
  Receipt,
  Recycle,
  Route,
  Scale,
  Shield,
  Store,
  TreePine,
  Truck,
  UserCog,
  Users,
  Vote,
  Waves,
  Wrench,
  Zap,
  Dumbbell,
  MapPin,
} from "lucide-react";

/** Shared CSMC department contact (display localized via `d()` on detail pages). */
export const DEPARTMENT_CONTACT_PHONE = "0240-2333536";

const SLUG_ICON: Record<string, LucideIcon> = {
  "municipal-commissioner": Landmark,
  "additional-commissioner-1": Users,
  "additional-commissioner-2": Users,
  "general-administration": UserCog,
  labour: HardHat,
  education: BookOpen,
  "tourism-development": MapPin,
  cultural: Palette,
  "fire-disaster-management": Flame,
  "solid-waste-management": Recycle,
  environment: Leaf,
  garden: TreePine,
  "kham-sukhna-river": Waves,
  "sports-swimming": Dumbbell,
  health: HeartPulse,
  tax: Receipt,
  "market-license": Store,
  "property-management": Building,
  bot: Building2,
  "animal-veterinary": PawPrint,
  "election-census": Vote,
  legal: Scale,
  "social-development": Users,
  library: Library,
  nulm: Home,
  "information-technology": Cpu,
  "information-public-relations": Megaphone,
  "central-stores": Package,
  pmay: HousePlus,
  "ramai-housing": HousePlus,
  roads: Route,
  "ramai-civil": HardHat,
  "solid-waste-civil": Recycle,
  buildings: Building2,
  "pmay-civil": HousePlus,
  "garden-civil": TreePine,
  drainage: Droplets,
  "drainage-special-east": Droplets,
  "drainage-special-central": Droplets,
  "drainage-special-west": Droplets,
  "water-supply-distribution": Droplets,
  "jayakwadi-water-civil": Waves,
  "jayakwadi-water-mechanical": Wrench,
  "city-water-mechanical": Wrench,
  "mechanical-vehicles": Truck,
  electrical: Zap,
  encroachment: Shield,
  security: Shield,
};

export function getDepartmentIcon(slug: string): LucideIcon {
  return SLUG_ICON[slug] ?? Building2;
}
